# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [3]:
print(np.__version__)
print(np.show_config())

1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Himanshu Sharma/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Himanshu Sharma/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Himanshu Sharma/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Himanshu Sharma/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Himanshu Sharma/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Himanshu Sharma/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Himanshu Sharma/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', No

#### 3. Create a null vector of size 10

In [4]:
arr = np.zeros(10)
print(arr)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array

In [5]:
arrsize = arr.size
arritem = arr.itemsize
print("{} bytes".format(arrsize*arritem))

80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [6]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [7]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [9]:
arr = np.arange(10,50,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45])

#### 8.  Reverse a vector (first element becomes last)

In [10]:
np.flipud(arr)

array([45, 40, 35, 30, 25, 20, 15, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
arr = np.random.randint(0,9,(3,3))
arr

array([[4, 8, 3],
       [5, 7, 8],
       [7, 4, 6]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [12]:
arr = np.array([1,2,0,0,4,0])
ans =  np.nonzero(arr)
ans

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix

In [16]:
arr=np.eye(3,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [17]:
np.random.random((3,3,3))

array([[[0.26232169, 0.6818494 , 0.76393633],
        [0.85741039, 0.14997834, 0.99960832],
        [0.20484138, 0.85320185, 0.21669863]],

       [[0.62913441, 0.57437358, 0.9065037 ],
        [0.17716703, 0.44231283, 0.33564937],
        [0.31069082, 0.40637644, 0.96350271]],

       [[0.9589091 , 0.84448946, 0.85738657],
        [0.1552101 , 0.06996499, 0.30914403],
        [0.46961283, 0.20639669, 0.7338732 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [18]:
arr = np.random.random((10,10))
a = np.max(arr)
b = np.min(arr)
print(a,b,sep="\n")

0.9955670733867035
0.0015414985401244197


#### 14. Create a random vector of size 30 and find the mean value

In [25]:
arr = np.random.random(30)
m=arr.mean()
m

0.4055181925996982

#### 15. Create a 2d array with 1 on the border and 0 inside

In [26]:
arr = np.ones((5,5))
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [27]:
arr = np.ones((5,5))
np.pad(arr,pad_width = 1, mode = 'constant',constant_values = 0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [28]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == (3 * 0.1))


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [29]:
arr = np.diag([1,2,3,4],-1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [30]:
check = np.zeros((8,8),dtype=int)
check[1::2,::2] = 1
check[::2,1::2] = 1
check

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [31]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)